apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: remote-server-guestbook-proj
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Project to configure argocd installation
  destinations:
  - namespace: 'guestbook'
    server: https://192.168.1.231:8443
  sourceRepos:
  - https://github.com/argoproj/argocd-example-apps
  